### ISSUE TITLE
_isnan is not valid for Mac OSX

### ISSUE THREAD

**Issue by gcoco** [sintegrial/qwtplot3d#3]
The recent addition of _isnan breaks builds on Mac OSX.

isnan is a valid replacement.

Can a conditional check for Q_OS_MAC be created somewhere that will define _isnan to be isnan.

Not 100% sure the best way to do this or I would submit a patch.

Thanks

**Comment by sintegrial** [comment]
Hi, 
Thanks for the info. Please submit the patch and we will merge it.
Best regards

**Comment by gcoco** [comment]
Thank you for the patch that you created. Mac now compiles.
