### ISSUE TITLE
'isnan': identifier not found

### ISSUE THREAD

**Issue by gambr** [sintegrial/qwtplot3d#5]
Hi,
I cloned the git repository yesterday and tried to build with both QtCreator and VS2010, on Windows 7, with QT 4.8.2.
I get the following error:

d:\3rd_party\qwtplot3d\qwtplot3d-qt4.8.6-vs2010-x86\include\qwt3d_types.h(247): error C3861: 'isnan': identifier not found

It seems Q_OS_WIN is not defined.

**Comment by gambr** [comment]
I added the following line:
DEFINES += Q_OS_WIN

in two files:
D:\3rd_party\qwtplot3d\qwtplot3d-qt4.8.6-vs2010-x86\src\src.pro (line 31)
D:\3rd_party\qwtplot3d\qwtplot3d-qt4.8.6-vs2010-x86\examples\common.pro (line 21)

and the build works fine except a bunch of warnings:

../src/corelib/global/qglobal.h(251): warning C4005: 'Q_OS_WIN' : macro redefinition

**Comment by sintegrial** [comment]
Hi,

there must be #include <QtGlobal> added to qwt3d_types.h before accessing the macro Q_OS_WIN.
It has been corrected now.
