### ISSUE TITLE
Release building issue in vs2015 x86

### ISSUE THREAD

**Issue by giorgio31** [sintegrial/qwtplot3d#9]
Hi,
In last qwtplot3d version, I am able to compile only the debug configuration. When I switch in Release configuration I get the following error:

_C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(392,5): warning MSB8028: The intermediate directory (Win32\Release\) contains files shared from another project (qwtplot3d.vcxproj).  This can lead to incorrect clean and rebuild behavior.
  Moc'ing qwt3d_extglwidget.h...
  Moc'ing qwt3d_gridplot.h...
  Moc'ing qwt3d_plot3d.h...
  Moc'ing qwt3d_surfaceplot.h...
  Generate moc_predefs.h
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 2_

Enviroment info:
  Visual Studio 2015
  Qt 5.8
  Platform x86

Any suggestion or tip?

Thanks in advance

Giorgio

**Comment by sintegrial** [comment]
Hi,
it looks like a Qt bug (see https://bugreports.qt.io/browse/QTBUG-58391),
should already be solved within Qt 5.9.
Just try to compile with the most recent Qt release.

Best regards
Sintegrial Technologies
